### ISSUE TITLE
Disabling pagination

### ISSUE THREAD

**Issue by TomCaserta** [tspvivek/refine-directus#14]
First of all thank you for creating this library.

I'm looking to just pull down a list of content and essentially ignore pagination. I've tried setting `pagination: { mode: 'off' }` when using the `useList` hook however it seemingly is not having an effect. 

I see in the code that it is defaulting to the first page and a set page size. I can set the page size to `-1` which I imagine will have the effect of returning all of the content but it looks like it will still make the aggregate count request. 

Am I correct in this statement? Would you be willing to accept a PR that will disable the aggregate count request and default the page size to -1 when the pagination mode is set to `off`?

Thanks,

**Comment by tspvivek** [comment]
You are correct, Addition to your fix we can return the length of the result as count instead of aggregate request to avoid breaking existing users, who might have used count in any means.

**Comment by tspvivek** [comment]
@TomCaserta Fixed as part of v1.0.37
