### ISSUE TITLE
Dataprovider returning rowCount as a string instead of a number when using useDatagrid MUI

### ISSUE THREAD

**Issue by Oumar24sh** [tspvivek/refine-directus#17]
Warning: Failed prop type: Invalid prop `count` of type `string` supplied to `ForwardRef(TablePaginationActions2)`, expected `number`

Added parseInt for the total count 
`
total: parseInt(total[0]?.countDistinct?.[aggregateField]) ?? 0,
`

**Comment by tspvivek** [comment]
Thanks for reporting the issue. Issue has been fixed now.
