### ISSUE TITLE
The demo is not working

### ISSUE THREAD

**Issue by Kamalito75** [tspvivek/refine-directus#5]
Hi. 
The demo at https://stackblitz.com/edit/tspvivek-refine-directus-ecshj4 is not working. The error message "TransportError : socket hang up" is displayed : 
![image](https://user-images.githubusercontent.com/37375878/195990582-9f5eee66-53d5-4b17-8b05-0f7dc5ce38ec.png)

**Comment by tspvivek** [comment]
Thanks for the update, directus team has blocked CORS request for Community Cloud
plan. I will host a demo instance and will update the demo.

**Comment by omeraplak** [comment]
> Thanks for the notifying, directus team has blocked CORS request for Community Cloud
> plan. I will host a demo instance and will update the demo.

Hey @tspvivek ,
Thank you for your attention. I will discuss this with the Directus team. I'll let you know if there's any progress ⚡️

**Comment by Kamalito75** [comment]
> Thanks for the notifying, directus team has blocked CORS request for Community Cloud plan. I will host a demo instance and will update the demo.

Thank you.

**Comment by tspvivek** [comment]
Fixed in new release.
