### ISSUE TITLE
Support of Refine v4

### ISSUE THREAD

**Issue by davidpp** [tspvivek/refine-directus#6]
Hi!

We are currently testing Refine and as we already use Directus.  As such, we are wondering if you were planning to update your dataprovider to the V4 of Refine?

Thanks!

**Comment by tspvivek** [comment]
Yes, We are working on it along with directus web socket support. You can expect by end of this month.

**Comment by omeraplak** [comment]
> Yes, We are working on it along with directus web socket support. You can expect by end of this month.

Wow, super cool! We look forward. Thank you for your great efforts 🍻

**Comment by tspvivek** [comment]
@davidpp @omeraplak Latest version released with refine v4 support, Using directus SDK v11, Liveprovider using directus realtime API and updated example.

**Comment by omeraplak** [comment]
> @davidpp @omeraplak Latest version released with refine v4 support, directus SDK v11, Liveprovider using directus realtime API and updated example.

Thank you :)
