### ISSUE TITLE
Sdk 12.0.0

### ISSUE THREAD

**Issue by onurbamaro** [tspvivek/refine-directus#7]
Hello! Thank you for creating this tool.

I'm new to "refine" and have been using Directus. I'm interested in trying out your package. I recently noticed that Directus has released SDK version 12.0.0.

Do you have plans to update your package accordingly?

**Comment by tspvivek** [comment]
Yes, Its coming soon, mostly in a week.

**Comment by tspvivek** [comment]
Updated to SDK v12 along with some enhancements
https://github.com/tspvivek/refine-directus/blob/master/package/README.md#change-log
